sap.ui.define(
  [],
  () => {
    'use strict';

    return {
      COMMON: 'ZHRXX_COMMON_SRV',
      LANCHPADSTATUS: 'ZHRXX_LANCHPADSTATUS_SRV',
      TMCOMMON: 'ZHRXX_TMCOMMON_SRV',
      // MYTIME: 'zhrxx_mytime_srv',
      MYTIME: 'ZHRXX_MYTIME_SRV',
      TIMEMANAGEMENT: 'ZHRXX_TIME_MANAGEMENT_SRV',
      FLEXIBLETIME: 'ZHRXX_FLEXIBLETIME_SRV',
      APPROVAL: 'ZHRXX_APPROVAL_SRV',
      HRCALENDAR: 'ZHRXX_HRCALENDAR_SRV',
      // PERSONALTIME: 'ZHREU_PERSONALTIME_SRV',
      // NIGHTWORK: 'ZHRKR_NIGHTWORK_SRV',
      // WORKTIME: 'ZHRKR_WORKTIME_TESNA_SRV',
    };
  },
  /* bExport= */ true
);
